### ISSUE TITLE
Observer Pattern

### ISSUE THREAD

**Issue by baristunar** [baristunar/design-patterns-tr#3]
Observer Pattern should be translated into Turkish.

Source: [patterns.dev](https://www.patterns.dev/posts/observer-pattern/)

**Comment by DenizCansever** [comment]
Haftaya başlayabilirim @baristunar

**Comment by baristunar** [comment]
Teşekkürler abi :) @DenizCansever

**Comment by DenizCansever** [comment]
@baristunar issue kapatabiliriz abi
