### ISSUE TITLE
Abstract Factory

### ISSUE THREAD

**Issue by baristunar** [baristunar/design-patterns-tr#31]
**Abstract Factory** patterni türkçeye çevrilmelidir.

* Kaynak önerisi: https://refactoring.guru/design-patterns/abstract-factory 
ya da belirlediğiniz bir kaynağı çevirebilirsiniz.

* Yazının başında kaynak vermeyi unutmayınız.
* Kimse üzerine assign etmediyse üzerinize assign edip başlayabilirsiniz.

--- 
Çeviri öncesi [dikkat edilmesi gerekenleri](https://github.com/baristunar/design-patterns-tr) okumayı unutmayınız.

--- 
Kolay gelsin :heart:  :rocket:

**Comment by dogancanulgu** [comment]
Alıyorum ✋

**Comment by dogancanulgu** [comment]
#70 konu mergelenmiştir
