### ISSUE TITLE
Adapter Pattern

### ISSUE THREAD

**Issue by baristunar** [baristunar/design-patterns-tr#34]
**Adapter** patterni türkçeye çevrilmelidir.

* Kaynak önerisi: https://refactoring.guru/design-patterns/adapter
ya da belirlediğiniz bir kaynağı çevirebilirsiniz.

* Yazının başında kaynak vermeyi unutmayınız.
* Kimse üzerine assign etmediyse üzerinize assign edip başlayabilirsiniz. 

---

Çeviri öncesi [dikkat edilmesi gerekenleri](https://github.com/baristunar/design-patterns-tr) okumayı unutmayınız.

---

Kolay gelsin :heart: :rocket:

**Comment by coderserdar** [comment]
I took this pattern to myself if that is suitable
