### ISSUE TITLE
Composite Pattern

### ISSUE THREAD

**Issue by baristunar** [baristunar/design-patterns-tr#36]
**Composite** patterni türkçeye çevrilmelidir.

* Kaynak önerisi: https://refactoring.guru/design-patterns/composite
ya da belirlediğiniz bir kaynağı çevirebilirsiniz.

* Yazının başında kaynak vermeyi unutmayınız.
* Kimse üzerine assign etmediyse üzerinize assign edip başlayabilirsiniz. 

---

Çeviri öncesi [dikkat edilmesi gerekenleri](https://github.com/baristunar/design-patterns-tr) okumayı unutmayınız.

---

Kolay gelsin :heart: :rocket:

**Comment by coderserdar** [comment]
I wanna take this design pattern
