### ISSUE TITLE
Slide Issue

### ISSUE THREAD

**Issue by coderserdar** [baristunar/design-patterns-tr#40]
Can we add some university's slides for design pattern which are in Turkish

**Comment by cengizcmataraci** [comment]
Merhaba, katkın için teşekkürler. Akademik materyal legal açıdan sorun yaratabilir, o materyalden bir yazı yazıp onu eklersen daha iyi olabilir. Ya da slide sahibi eğitmenin onayı olursa o da olur.

**Comment by coderserdar** [comment]
Bu slaytlar öğrenci iken bize verilmiş slaytlardı hocam. Ders içeriği kapsamında verilmişti.
İsterseniz önden size maille bir örnek göndereyim. Sorun olacaksa alternatif bir çözüme gidebiliriz

**Comment by baristunar** [comment]
Öncelikle teşekkür ederiz desteğin için. Slayt konusuna gelince slayttan ziyade Readme dosyasında yazılması daha uygun gibi geliyor bana

**Comment by coderserdar** [comment]
Ok buna göre bir çalışma yapmaya çalışayım hocam o zaman
