### ISSUE TITLE
Mixin Pattern

### ISSUE THREAD

**Issue by baristunar** [baristunar/design-patterns-tr#5]
Mixin Pattern should be translated into Turkish.

Source: [patterns.dev](https://www.patterns.dev/posts/mixin-pattern/)

**Comment by Haticesurumlu** [comment]
Bunu alabilirimmm 😊🎈 @baristunar

**Comment by baristunar** [comment]
Teşekkürlerr kolay gelsin @Haticesurumlu  🚀
