### ISSUE TITLE
HOC Pattern

### ISSUE THREAD

**Issue by baristunar** [baristunar/design-patterns-tr#7]
HOC (Higher Order Component) Pattern should be translated into Turkish.

Source: [patterns.dev](https://www.patterns.dev/posts/hoc-pattern/)

**Comment by ismailgunayy** [comment]
Aldım, çeviriye başlıyorum ✋🏻

**Comment by ismailgunayy** [comment]
Alıyorum ✋🏻

**Comment by baristunar** [comment]
Teşekkürler abi kolay gelsin :)

**Comment by ismailgunayy** [comment]
Biraz geç oldu kusura bakmayın, PR açtım :)
