### ISSUE TITLE
Render Props Pattern

### ISSUE THREAD

**Issue by baristunar** [baristunar/design-patterns-tr#8]
Render Props Pattern should be translated into Turkish.

Source: [patterns.dev](https://www.patterns.dev/posts/render-props-pattern/)

**Comment by olcaykaplan** [comment]
bu konuyu da ben alabilir miyim?

**Comment by baristunar** [comment]
Selamlar tabi ki boşta gördüğün taskı direkt assign edebilirsin üzerine :) Desteğin için teşekkürler, kolay gelsin :rocket:
